services:
  - type: web
    name: coursehub
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: coursehub-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL_ID
        sync: false
      - key: SLACK_TEST_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
    healthCheckPath: /api/health
    
databases:
  - name: coursehub-db
    databaseName: coursehub
    user: coursehub_user
    plan: free